
package org.geovistory.toolbox.streams.entity;

import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.CommunityEntityKey;
import org.geovistory.toolbox.streams.avro.CommunityEntityTopStatementsValue;
import org.geovistory.toolbox.streams.avro.ProjectEntityKey;
import org.geovistory.toolbox.streams.avro.ProjectEntityTopStatementsValue;
import org.geovistory.toolbox.streams.entity.processors.community.CommunityEntityTopStatements;
import org.geovistory.toolbox.streams.entity.processors.project.ProjectEntityTopStatements;
import org.geovistory.toolbox.streams.lib.ConfluentAvroSerdes;
import org.geovistory.toolbox.streams.lib.InputTopicHelper;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
public class RegisterInnerTopic extends InputTopicHelper {
    public ConfluentAvroSerdes avroSerdes;

    public RegisterInnerTopic(StreamsBuilder builder) {
        super(builder);
        this.avroSerdes = new ConfluentAvroSerdes();
    }


    public KTable<ProjectEntityKey, ProjectEntityTopStatementsValue> projectEntityTopStatementsTable() {
        return getTable(ProjectEntityTopStatements.output.TOPICS.project_entity_top_statements,
                avroSerdes.ProjectEntityKey(), avroSerdes.ProjectEntityTopStatementsValue());
    }

    public KStream<ProjectEntityKey, ProjectEntityTopStatementsValue> projectEntityTopStatementsStream() {
        return getStream(ProjectEntityTopStatements.output.TOPICS.project_entity_top_statements,
                avroSerdes.ProjectEntityKey(), avroSerdes.ProjectEntityTopStatementsValue());
    }

    public KTable<CommunityEntityKey, CommunityEntityTopStatementsValue> communityEntityTopStatementsTable(String nameSupplement) {
        return getTable(CommunityEntityTopStatements.getOutputTopicName(nameSupplement),
                avroSerdes.CommunityEntityKey(), avroSerdes.CommunityEntityTopStatementsValue());
    }

    public KStream<CommunityEntityKey, CommunityEntityTopStatementsValue> communityEntityTopStatementsStream(String nameSupplement) {
        return getStream(CommunityEntityTopStatements.getOutputTopicName(nameSupplement),
                avroSerdes.CommunityEntityKey(), avroSerdes.CommunityEntityTopStatementsValue());
    }

}
