package org.geovistory.toolbox.streams.fulltext;

import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.ConfluentAvroSerdes;
import org.geovistory.toolbox.streams.lib.InputTopicHelper;

/**
 * This class provides helper methods to register
 * source topics (topics consumed but not generated by this app)
 */
public class RegisterInputTopic extends InputTopicHelper {
    public ConfluentAvroSerdes avroSerdes;

    public RegisterInputTopic(StreamsBuilder builder) {
        super(builder);
        this.avroSerdes = new ConfluentAvroSerdes();
    }


    public KTable<ProjectEntityKey, ProjectEntityLabelConfigValue> projectEntityWithLabelConfigTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_WITH_LABEL_CONFIG,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityLabelConfigValue()
        );
    }


    public KTable<ProjectTopStatementsKey, ProjectTopStatementsValue> projectTopStatementsTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_TOP_STATEMENTS,
                avroSerdes.ProjectTopStatementsKey(),
                avroSerdes.ProjectTopStatementsValue()
        );
    }


    public KTable<ProjectFieldLabelKey, ProjectFieldLabelValue> projectPropertyLabelTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_PROPERTY_LABEL,
                avroSerdes.ProjectPropertyLabelKey(),
                avroSerdes.ProjectPropertyLabelValue()
        );
    }


    public KTable<CommunityEntityKey, CommunityEntityLabelConfigValue> communityEntityWithLabelConfigTable() {
        return getTable(
                Env.INSTANCE.TOPIC_COMMUNITY_ENTITY_WITH_LABEL_CONFIG,
                avroSerdes.CommunityEntityKey(),
                avroSerdes.CommunityEntityLabelConfigValue()
        );
    }


    public KTable<CommunityTopStatementsKey, CommunityTopStatementsValue> communityTopStatementsTable() {
        return getTable(
                Env.INSTANCE.TOPIC_COMMUNITY_TOP_STATEMENTS,
                avroSerdes.CommunityTopStatementsKey(),
                avroSerdes.CommunityTopStatementsValue()
        );
    }


    public KTable<CommunityPropertyLabelKey, CommunityPropertyLabelValue> communityPropertyLabelTable() {
        return getTable(
                Env.INSTANCE.TOPIC_COMMUNITY_PROPERTY_LABEL,
                avroSerdes.CommunityPropertyLabelKey(),
                avroSerdes.CommunityPropertyLabelValue()
        );
    }


}