package org.geovistory.toolbox.streams.fulltext;

import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.TsRegisterInputTopic;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

/**
 * This class provides helper methods to register
 * source topics (topics consumed but not generated by this app)
 */
@ApplicationScoped
public class RegisterInputTopic extends TsRegisterInputTopic {

    @Inject
    AvroSerdes avroSerdes;
    @Inject
    public BuilderSingleton builderSingleton;

    @Inject
    public InputTopicNames inputTopicNames;

    public RegisterInputTopic(AvroSerdes avroSerdes, BuilderSingleton builderSingleton, InputTopicNames inputTopicNames) {
        this.avroSerdes = avroSerdes;
        this.builderSingleton = builderSingleton;
        this.inputTopicNames = inputTopicNames;
    }

    public KTable<ProjectEntityKey, ProjectEntityLabelConfigValue> projectEntityWithLabelConfigTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.projectEntityWithLabelConfig,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityLabelConfigValue()
        );
    }


    public KTable<ProjectTopStatementsKey, ProjectTopStatementsValue> projectTopStatementsTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.projectTopStatements,
                avroSerdes.ProjectTopStatementsKey(),
                avroSerdes.ProjectTopStatementsValue()
        );
    }


    public KTable<ProjectFieldLabelKey, ProjectFieldLabelValue> projectPropertyLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.projectPropertyLabel,
                avroSerdes.ProjectPropertyLabelKey(),
                avroSerdes.ProjectPropertyLabelValue()
        );
    }


    public KTable<CommunityEntityKey, CommunityEntityLabelConfigValue> communityEntityWithLabelConfigTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.communityEntityWithLabelConfig,
                avroSerdes.CommunityEntityKey(),
                avroSerdes.CommunityEntityLabelConfigValue()
        );
    }


    public KTable<CommunityTopStatementsKey, CommunityTopStatementsValue> communityTopStatementsTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.communityTopStatements,
                avroSerdes.CommunityTopStatementsKey(),
                avroSerdes.CommunityTopStatementsValue()
        );
    }


    public KTable<CommunityPropertyLabelKey, CommunityPropertyLabelValue> communityPropertyLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.communityPropertyLabel,
                avroSerdes.CommunityPropertyLabelKey(),
                avroSerdes.CommunityPropertyLabelValue()
        );
    }


}