version: '2'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.31.1-kafka-3.1.2
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.31.1-kafka-3.1.2
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://localhost:9092"
      SCHEMA_REGISTRY_HOST_NAME: http://localhost:8081
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: FORWARD

  kafka-ui:
    image: provectuslabs/kafka-ui:f9906b5d307da11303177c4ddc04d4658c4ebfab
    depends_on:
      - kafka
    ports:
      - "8888:8080"
    environment:
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "schema-registry:8081"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
