
package org.geovistory.toolbox.streams.project.entity.preview;

import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.ConfluentAvroSerdes;
import org.geovistory.toolbox.streams.lib.InputTopicHelper;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
public class RegisterInputTopic extends InputTopicHelper {
    public ConfluentAvroSerdes avroSerdes;

    public RegisterInputTopic(StreamsBuilder builder) {
        super(builder);
        this.avroSerdes = new ConfluentAvroSerdes();
    }


    public KTable<ProjectEntityKey, ProjectEntityValue> projectEntityTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityValue()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityLabelValue> projectEntityLabelTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_LABEL,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityLabelValue()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityTypeValue> projectEntityTypeTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_TYPE,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityTypeValue()
        );
    }

    public KTable<ProjectEntityKey, TimeSpanValue> projectEntityTimeSpanTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_TIME_SPAN,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.TimeSpanValue()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityFulltextValue> projectEntityFulltextTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_FULLTEXT,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityFulltextValue()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityClassLabelValue> projectEntityClassLabelTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_CLASS_LABEL,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityClassLabelValue()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityClassMetadataValue> projectEntityClassMetadataTable() {
        return getTable(
                Env.INSTANCE.TOPIC_PROJECT_ENTITY_CLASS_METADATA,
                avroSerdes.ProjectEntityKey(),
                avroSerdes.ProjectEntityClassMetadataValue()
        );
    }

}
