/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.geovistory.toolbox.streams.nodes;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.geovistory.toolbox.streams.lib.Admin;
import org.geovistory.toolbox.streams.lib.AppConfig;
import org.geovistory.toolbox.streams.nodes.processors.Nodes;

import static org.geovistory.toolbox.streams.nodes.BuildProperties.getDockerImageTag;
import static org.geovistory.toolbox.streams.nodes.BuildProperties.getDockerTagSuffix;

class App {
    public static void main(String[] args) {


        StreamsBuilder builder = new StreamsBuilder();

        // add processors of sub-topologies
        addSubTopologies(builder);

        // build the topology
        var topology = builder.build();

        System.out.println(topology.describe());

        // create topics in advance to ensure correct configuration (partition, compaction, ect.)
        createTopics();

        // print configuration information
        System.out.println("Starting Toolbox Streams App " + getDockerImageTag() + ":" + getDockerTagSuffix());
        System.out.println("With config:");
        AppConfig.INSTANCE.printConfigs();

        // create the streams app
        // noinspection resource
        KafkaStreams streams = new KafkaStreams(topology, AppConfig.getConfig());

        // close Kafka Streams when the JVM shuts down (e.g. SIGTERM)
        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));

        // start streaming!
        streams.start();
    }

    private static void addSubTopologies(StreamsBuilder builder) {
        var inputTopics = new RegisterInputTopic(builder);

        // register input topics as KTables
        var infResourceStream = inputTopics.infResourceStream();
        var infLanguageStream = inputTopics.infLanguageStream();
        var infAppellationStream = inputTopics.infAppellationStream();
        var infLangStringStream = inputTopics.infLangStringStream();
        var infPlaceStream = inputTopics.infPlaceStream();
        var infTimePrimitiveStream = inputTopics.infTimePrimitiveStream();
        var infDimensionStream = inputTopics.infDimensionStream();
        var datDigitalStream = inputTopics.datDigitalStream();
        var tabCellStream = inputTopics.tabCellStream();

        // add sub-topology StatementEnriched
        Nodes.addProcessors(
                infResourceStream,
                infLanguageStream,
                infAppellationStream,
                infLangStringStream,
                infPlaceStream,
                infTimePrimitiveStream,
                infDimensionStream,
                datDigitalStream,
                tabCellStream
        );
    }

    private static void createTopics() {
        var admin = new Admin();

        var outputTopicPartitions = Integer.parseInt(AppConfig.INSTANCE.getOutputTopicPartitions());
        var outputTopicReplicationFactor = Short.parseShort(AppConfig.INSTANCE.getOutputTopicReplicationFactor());

        // create output topics (with number of partitions and delete.policy=compact)
        admin.createOrConfigureTopics(new String[]{
                Nodes.output.TOPICS.nodes,
        }, outputTopicPartitions, outputTopicReplicationFactor);


    }


}
