
package org.geovistory.toolbox.streams.project.config;

import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.ConfluentAvroSerdes;
import org.geovistory.toolbox.streams.lib.InputTopicHelper;
import org.geovistory.toolbox.streams.project.config.processors.*;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
public class RegisterInnerTopic extends InputTopicHelper {

    public ConfluentAvroSerdes avroSerdes;

    public RegisterInnerTopic(StreamsBuilder builder) {
        super(builder);
        this.avroSerdes = new ConfluentAvroSerdes();
    }

    public KStream<ProjectProfileKey, ProjectProfileValue> projectProfileStream() {
        return getStream(ProjectProfiles.output.TOPICS.project_profile,
                avroSerdes.ProjectProfileKey(), avroSerdes.ProjectProfileValue());
    }


    public KStream<GeovClassLabelKey, GeovClassLabelValue> geovClassLabelStream() {
        return getStream(GeovClassLabel.output.TOPICS.geov_class_label,
                avroSerdes.GeovClassLabelKey(), avroSerdes.GeovClassLabelValue());
    }

    public KTable<GeovClassLabelKey, GeovClassLabelValue> geovClassLabelTable() {
        return getTable(GeovClassLabel.output.TOPICS.geov_class_label,
                avroSerdes.GeovClassLabelKey(), avroSerdes.GeovClassLabelValue());
    }


    public KStream<ProjectClassKey, ProjectClassValue> projectClassStream() {
        return getStream(ProjectClass.output.TOPICS.project_class,
                avroSerdes.ProjectClassKey(), avroSerdes.ProjectClassValue());
    }

    public KTable<ProjectClassKey, ProjectClassValue> projectClassTable() {
        return getTable(ProjectClass.output.TOPICS.project_class,
                avroSerdes.ProjectClassKey(), avroSerdes.ProjectClassValue());
    }


    public KStream<GeovPropertyLabelKey, GeovPropertyLabelValue> geovPropertyLabelStream() {
        return getStream(GeovPropertyLabel.output.TOPICS.geov_property_label,
                avroSerdes.GeovPropertyLabelKey(), avroSerdes.GeovPropertyLabelValue());
    }

    public KTable<GeovPropertyLabelKey, GeovPropertyLabelValue> geovPropertyLabelTable() {
        return getTable(GeovPropertyLabel.output.TOPICS.geov_property_label,
                avroSerdes.GeovPropertyLabelKey(), avroSerdes.GeovPropertyLabelValue());
    }

    public KStream<ProjectPropertyKey, ProjectPropertyValue> projectPropertyStream() {
        return getStream(ProjectProperty.output.TOPICS.project_property,
                avroSerdes.ProjectPropertyKey(), avroSerdes.ProjectPropertyValue());
    }


    public KTable<CommunityEntityLabelConfigKey, CommunityEntityLabelConfigValue> communityEntityLabelConfigTable() {
        return getTable(CommunityEntityLabelConfig.output.TOPICS.community_entity_label_config,
                avroSerdes.CommunityEntityLabelConfigKey(), avroSerdes.CommunityEntityLabelConfigValue());
    }


}
