/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.geovistory.toolbox.streams.rdf;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.geovistory.toolbox.streams.lib.Admin;
import org.geovistory.toolbox.streams.lib.AppConfig;
import org.geovistory.toolbox.streams.rdf.processors.project.ProjectStatementToUri;

import java.util.ArrayList;

import static org.geovistory.toolbox.streams.rdf.BuildProperties.getDockerImageTag;
import static org.geovistory.toolbox.streams.rdf.BuildProperties.getDockerTagSuffix;

class App {
    public static void main(String[] args) {


        StreamsBuilder builder = new StreamsBuilder();

        // add processors of sub-topologies
        addSubTopologies(builder);

        // build the topology
        var topology = builder.build();

        System.out.println(topology.describe());

        // create topics in advance to ensure correct configuration (partition, compaction, ect.)
        createTopics();

        // print configuration information
        System.out.println("Starting Toolbox Streams App " + getDockerImageTag() + ":" + getDockerTagSuffix());
        System.out.println("With config:");
        AppConfig.INSTANCE.printConfigs();

        // create the streams app
        // noinspection resource
        KafkaStreams streams = new KafkaStreams(topology, AppConfig.getConfig());

        // close Kafka Streams when the JVM shuts down (e.g. SIGTERM)
        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));

        // start streaming!
        streams.start();
    }

    private static void addSubTopologies(StreamsBuilder builder) {
        var inputTopics = new RegisterInputTopic(builder);

        addProjectView(builder, inputTopics);
        //addCommunityView(builder, inputTopics, "toolbox");
        //addMergedView(builder, "toolbox");
    }

    private static void addProjectView(StreamsBuilder builder, RegisterInputTopic inputTopics) {
        // register input topics as KStreams
        var projectStatementWithEntityStream = inputTopics.projectStatementWithEntityStream();

        // add sub-topology ProjectStatementToUri
        ProjectStatementToUri.addProcessors(builder,
                projectStatementWithEntityStream
        );
    }

    private static void createTopics() {
        var admin = new Admin();

        var outputTopicPartitions = Integer.parseInt(AppConfig.INSTANCE.getOutputTopicPartitions());
        var outputTopicReplicationFactor = Short.parseShort(AppConfig.INSTANCE.getOutputTopicReplicationFactor());

        // create output topics (with number of partitions and delete.policy=compact)
        var topics = new ArrayList<String>();
        topics.add(ProjectStatementToUri.output.TOPICS.project_rdf);
        // topics.add(CommunityEntityPreview.getOutputTopicName("toolbox")); TODO do not forget to add community output topic when available
        admin.createOrConfigureTopics(topics, outputTopicPartitions, outputTopicReplicationFactor);

    }

}
