package org.geovistory.toolbox.streams.entity.label;

import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.ConfluentAvroSerdes;
import org.geovistory.toolbox.streams.lib.InputTopicHelper;

/**
 * This class provides helper methods to register
 * source topics (topics consumed but not generated by this app)
 */
public class RegisterInputTopics extends InputTopicHelper {
    public ConfluentAvroSerdes avroSerdes;

    public RegisterInputTopics(StreamsBuilder builder) {
        super(builder);
        this.avroSerdes = new ConfluentAvroSerdes();
    }

    public KTable<dev.projects.info_proj_rel.Key, dev.projects.info_proj_rel.Value> proInfoProjRelTable() {
        return getRepartitionedTable(
                DbTopicNames.pro_info_proj_rel.getName(),
                avroSerdes.ProInfoProjRelKey(),
                avroSerdes.ProInfoProjRelValue()
        );
    }


    public KTable<dev.information.resource.Key, dev.information.resource.Value> infResourceTable() {
        return getRepartitionedTable(
                DbTopicNames.inf_resource.getName(),
                avroSerdes.InfResourceKey(),
                avroSerdes.InfResourceValue()
        );
    }


    public KTable<dev.information.statement.Key, StatementEnrichedValue> statementWithLiteralTable() {
        return getTable(Env.INSTANCE.TOPIC_STATEMENT_WITH_LITERAL,
                avroSerdes.InfStatementKey(), avroSerdes.StatementEnrichedValue());
    }

    public KTable<dev.information.statement.Key, StatementEnrichedValue> statementWithEntityTable() {
        return getTable(Env.INSTANCE.TOPIC_STATEMENT_WITH_ENTITY,
                avroSerdes.InfStatementKey(), avroSerdes.StatementEnrichedValue());
    }


    public KTable<ProjectClassKey, ProjectEntityLabelConfigValue> projectEntityLabelConfigTable() {
        return getRepartitionedTable(Env.INSTANCE.TOPIC_PROJECT_ENTITY_LABEL_CONFIG,
                avroSerdes.ProjectClassKey(), avroSerdes.ProjectEntityLabelConfigValue());
    }

    public KTable<CommunityEntityLabelConfigKey, CommunityEntityLabelConfigValue> communityEntityLabelConfigTable() {
        return getRepartitionedTable(Env.INSTANCE.TOPIC_COMMUNITY_ENTITY_LABEL_CONFIG,
                avroSerdes.CommunityEntityLabelConfigKey(), avroSerdes.CommunityEntityLabelConfigValue());
    }

}