/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.geovistory.toolbox.streams.field.changes;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.geovistory.toolbox.streams.field.changes.processors.ProjectFieldChange;
import org.geovistory.toolbox.streams.lib.Admin;
import org.geovistory.toolbox.streams.lib.AppConfig;

import java.util.ArrayList;

import static org.geovistory.toolbox.streams.field.changes.BuildProperties.getDockerImageTag;
import static org.geovistory.toolbox.streams.field.changes.BuildProperties.getDockerTagSuffix;

class App {
    public static void main(String[] args) {


        StreamsBuilder builder = new StreamsBuilder();

        // add processors of sub-topologies
        addSubTopologies(builder);

        // get config
        var config = AppConfig.getConfig();

        // print config
        AppConfig.INSTANCE.printConfigs();

        // build the topology
        var topology = builder.build(config);

        // print topology
        System.out.println(topology.describe());

        // create topics in advance to ensure correct configuration (partition, compaction, ect.)
        createTopics();

        // print configuration information
        System.out.println("Starting Toolbox Streams App " + getDockerImageTag() + ":" + getDockerTagSuffix());
        System.out.println("With config:");

        // create the streams app
        // noinspection resource
        KafkaStreams streams = new KafkaStreams(topology, config);

        // close Kafka Streams when the JVM shuts down (e.g. SIGTERM)
        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));

        // start streaming!
        streams.start();
    }

    private static void addSubTopologies(StreamsBuilder builder) {
        var inputTopics = new RegisterInputTopic(builder);

        // register input topics as KTables
        var proInfoProjRelTable = inputTopics.proInfoProjRelTable();
        var infStatementTable = inputTopics.infStatementTable();

        // add sub-topology ProjectFieldChange
        ProjectFieldChange.addProcessors(builder,
                infStatementTable,
                proInfoProjRelTable
        );

    }

    private static void createTopics() {
        var admin = new Admin();

        var outputTopicPartitions = Integer.parseInt(AppConfig.INSTANCE.getOutputTopicPartitions());
        var outputTopicReplicationFactor = Short.parseShort(AppConfig.INSTANCE.getOutputTopicReplicationFactor());

        // create output topics (with number of partitions and delete.policy=compact)
        var topics = new ArrayList<String>();
        topics.add(ProjectFieldChange.output.TOPICS.project_field_change);
        admin.createOrConfigureTopics(topics, outputTopicPartitions, outputTopicReplicationFactor);

    }


}
