package org.geovistory.toolbox.streams.base.config;

import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.TsRegisterInputTopic;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

/**
 * This class provides helper methods to register
 * source topics (topics consumed but not generated by this app)
 */

@ApplicationScoped
public class RegisterInputTopic extends TsRegisterInputTopic {

    @Inject
    AvroSerdes avroSerdes;
    @Inject
    public BuilderSingleton builderSingleton;

    @Inject
    public InputTopicNames inputTopicNames;

    RegisterInputTopic() {
    }

    public RegisterInputTopic(AvroSerdes avroSerdes, BuilderSingleton builderSingleton, InputTopicNames inputTopicNames) {
        this.avroSerdes = avroSerdes;
        this.builderSingleton = builderSingleton;
        this.inputTopicNames = inputTopicNames;
    }


    public KStream<ts.projects.text_property.Key, ts.projects.text_property.Value> proTextPropertyStream() {
        return getRepartitionedStream(
                builderSingleton.builder,
                inputTopicNames.proTextProperty(),
                avroSerdes.ProTextPropertyKey(),
                avroSerdes.ProTextPropertyValue()
        );
    }

    public KTable<ts.projects.dfh_profile_proj_rel.Key, ts.projects.dfh_profile_proj_rel.Value> proProfileProjRelTable() {
        return getRepartitionedTable(
                builderSingleton.builder,
                inputTopicNames.proProfileProjRel(),
                avroSerdes.ProProfileProjRelKey(),
                avroSerdes.ProProfileProjRelValue()
        );
    }


    public KTable<ts.projects.project.Key, ts.projects.project.Value> proProjectTable() {
        return getRepartitionedTable(
                builderSingleton.builder,
                inputTopicNames.proProject(),
                avroSerdes.ProProjectKey(),
                avroSerdes.ProProjectValue()
        );
    }

    public KStream<ts.system.config.Key, ts.system.config.Value> sysConfigStream() {
        return getRepartitionedStream(
                builderSingleton.builder,
                inputTopicNames.sysConfig(),
                avroSerdes.SysConfigKey(),
                avroSerdes.SysConfigValue()
        );
    }

    public KStream<ts.projects.entity_label_config.Key, ts.projects.entity_label_config.Value> proEntityLabelConfigStream() {
        return getStream(
                builderSingleton.builder,
                inputTopicNames.proEntityLabelConfig(),
                avroSerdes.ProEntityLabelConfigKey(),
                avroSerdes.ProEntityLabelConfigValue()
        );
    }

    public KStream<OntomeClassKey, OntomeClassValue> ontomeClassStream() {
        return getStream(
                builderSingleton.builder,
                inputTopicNames.ontomeClass(),
                avroSerdes.OntomeClassKey(), avroSerdes.OntomeClassValue());
    }

    public KStream<OntomePropertyKey, OntomePropertyValue> ontomePropertyStream() {
        return getStream(
                builderSingleton.builder,
                inputTopicNames.ontomeProperty(),
                avroSerdes.OntomePropertyKey(), avroSerdes.OntomePropertyValue());
    }


    public KStream<OntomeClassLabelKey, OntomeClassLabelValue> ontomeClassLabelStream() {
        return getStream(
                builderSingleton.builder,
                inputTopicNames.ontomeClassLabel(),
                avroSerdes.OntomeClassLabelKey(), avroSerdes.OntomeClassLabelValue());
    }

    public KTable<OntomeClassLabelKey, OntomeClassLabelValue> ontomeClassLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.ontomeClassLabel(),
                avroSerdes.OntomeClassLabelKey(), avroSerdes.OntomeClassLabelValue());
    }

    public KStream<OntomePropertyLabelKey, OntomePropertyLabelValue> ontomePropertyLabelStream() {
        return getStream(
                builderSingleton.builder,
                inputTopicNames.ontomePropertyLabel(),
                avroSerdes.OntomePropertyLabelKey(), avroSerdes.OntomePropertyLabelValue());
    }

}