/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.geovistory.toolbox.streams.statement.object;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.geovistory.toolbox.streams.lib.Admin;
import org.geovistory.toolbox.streams.lib.AppConfig;
import org.geovistory.toolbox.streams.statement.object.processors.StatementObject;

import java.util.ArrayList;
import java.util.Objects;

import static org.geovistory.toolbox.streams.statement.object.BuildProperties.getDockerImageTag;
import static org.geovistory.toolbox.streams.statement.object.BuildProperties.getDockerTagSuffix;


class App {
    public static void main(String[] args) {


        StreamsBuilder builder = new StreamsBuilder();

        // add processors of sub-topologies
        addSubTopologies(builder);

        // build the topology
        var topology = builder.build();

        System.out.println(topology.describe());

        // create topics in advance to ensure correct configuration (partition, compaction, ect.)
        createTopics();

        // print configuration information
        System.out.println("Starting Toolbox Streams App " + getDockerImageTag() + ":" + getDockerTagSuffix());
        System.out.println("With config:");
        AppConfig.INSTANCE.printConfigs();

        // create the streams app
        // noinspection resource
        KafkaStreams streams = new KafkaStreams(topology, AppConfig.getConfig());

        // close Kafka Streams when the JVM shuts down (e.g. SIGTERM)
        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));

        // start streaming!
        streams.start();
    }

    private static void addSubTopologies(StreamsBuilder builder) {
        var inputTopics = new RegisterInputTopic(builder);

        // register input topics as KTables
        var statementWithSubjectTable = inputTopics.statementWithSubjectTable();
        var nodeTable = inputTopics.nodeTable();

        // add sub-topology StatementEnriched
        StatementObject.addProcessors(
                statementWithSubjectTable,
                nodeTable
        );
    }

    private static void createTopics() {
        var admin = new Admin();

        var outputTopicPartitions = Integer.parseInt(AppConfig.INSTANCE.getOutputTopicPartitions());
        var outputTopicReplicationFactor = Short.parseShort(AppConfig.INSTANCE.getOutputTopicReplicationFactor());

        var topics = new ArrayList<String>();
        topics.add(StatementObject.output.TOPICS.statement_with_entity);
        topics.add(StatementObject.output.TOPICS.statement_with_literal);
        topics.add(StatementObject.output.TOPICS.statement_other);
        if (Objects.equals(Env.INSTANCE.CREATE_OUTPUT_FOR_POSTGRES, "true")) {
            topics.add(StatementObject.output.TOPICS.statement_enriched_flat);
        }
        // create output topics (with number of partitions and delete.policy=compact)
        admin.createOrConfigureTopics(topics, outputTopicPartitions, outputTopicReplicationFactor);

    }


}
