
package org.geovistory.toolbox.streams.entity.preview;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.apache.kafka.streams.kstream.KTable;
import org.geovistory.toolbox.streams.avro.*;
import org.geovistory.toolbox.streams.lib.TsRegisterInputTopic;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
@ApplicationScoped
public class RegisterInputTopic extends TsRegisterInputTopic {

    @Inject
    ConfiguredAvroSerde avroSerdes;
    @Inject
    public BuilderSingleton builderSingleton;

    @Inject
    public InputTopicNames inputTopicNames;



    public KTable<ProjectEntityKey, ProjectEntityValue> projectEntityTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntity(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityLabelValue> projectEntityLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityLabel(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityTypeValue> projectEntityTypeTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityType(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, TimeSpanValue> projectEntityTimeSpanTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityTimeSpan(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityFulltextValue> projectEntityFulltextTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityFulltext(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityClassLabelValue> projectEntityClassLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityClassLabel(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<ProjectEntityKey, ProjectEntityClassMetadataValue> projectEntityClassMetadataTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getProjectEntityClassMetadata(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }


    public KTable<CommunityEntityKey, CommunityEntityValue> communityEntityTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntity(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, CommunityEntityLabelValue> communityEntityLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityLabel(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, CommunityEntityTypeValue> communityEntityTypeTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityType(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, TimeSpanValue> communityEntityTimeSpanTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityTimeSpan(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, CommunityEntityFulltextValue> communityEntityFulltextTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityFulltext(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, CommunityEntityClassLabelValue> communityEntityClassLabelTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityClassLabel(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

    public KTable<CommunityEntityKey, CommunityEntityClassMetadataValue> communityEntityClassMetadataTable() {
        return getTable(
                builderSingleton.builder,
                inputTopicNames.getCommunityEntityClassMetadata(),
                avroSerdes.key(),
                avroSerdes.value()
        );
    }

}
