
package org.geovistory.toolbox.streams.entity.preview;

import org.apache.kafka.streams.kstream.KStream;
import org.geovistory.toolbox.streams.avro.CommunityEntityKey;
import org.geovistory.toolbox.streams.avro.EntityPreviewValue;
import org.geovistory.toolbox.streams.avro.ProjectEntityKey;
import org.geovistory.toolbox.streams.lib.TsRegisterInputTopic;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
@ApplicationScoped
public class RegisterInnerTopic extends TsRegisterInputTopic {

    @Inject
    AvroSerdes avroSerdes;
    @Inject
    public BuilderSingleton builderSingleton;
    @Inject
    OutputTopicNames outputTopicNames;

    public RegisterInnerTopic(AvroSerdes avroSerdes, BuilderSingleton builderSingleton, OutputTopicNames outputTopicNames) {
        this.avroSerdes = avroSerdes;
        this.builderSingleton = builderSingleton;
        this.outputTopicNames = outputTopicNames;
    }


    public KStream<ProjectEntityKey, EntityPreviewValue> projectEntityPreviewStream() {
        return getStream(
                builderSingleton.builder,
                outputTopicNames.projectEntityPreview(),
                avroSerdes.ProjectEntityKey(), avroSerdes.EntityPreviewValue());
    }

    public KStream<CommunityEntityKey, EntityPreviewValue> communityEntityPreviewStream() {
        return getStream(
                builderSingleton.builder,
                outputTopicNames.communityEntityPreview(),
                avroSerdes.CommunityEntityKey(), avroSerdes.EntityPreviewValue());
    }

}
