
package org.geovistory.toolbox.streams.entity.preview;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.apache.kafka.streams.kstream.KStream;
import org.geovistory.toolbox.streams.avro.CommunityEntityKey;
import org.geovistory.toolbox.streams.avro.EntityPreviewValue;
import org.geovistory.toolbox.streams.avro.ProjectEntityKey;
import org.geovistory.toolbox.streams.lib.TsRegisterInputTopic;

/**
 * This class provides helper methods to register
 * output topics (generated by this app).
 * These helper methods are mainly used for testing.
 */
@ApplicationScoped
public class RegisterInnerTopic extends TsRegisterInputTopic {

    @Inject
    ConfiguredAvroSerde avroSerdes;
    @Inject
    public BuilderSingleton builderSingleton;
    @Inject
    OutputTopicNames outputTopicNames;


    public KStream<ProjectEntityKey, EntityPreviewValue> projectEntityPreviewStream() {
        return getStream(
                builderSingleton.builder,
                outputTopicNames.projectEntityPreview(),
                avroSerdes.key(), avroSerdes.value());
    }

    public KStream<CommunityEntityKey, EntityPreviewValue> communityEntityPreviewStream() {
        return getStream(
                builderSingleton.builder,
                outputTopicNames.communityEntityPreview(),
                avroSerdes.key(), avroSerdes.value());
    }

}
