name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      app:
        description: "Deploy App"
        required: true
        type: choice
        options:
          - toolbox-streams
          - toolbox-streams-base-model
          - toolbox-streams-field-changes
          - toolbox-streams-base-config
          - toolbox-streams-entity
          - toolbox-streams-entity-label
          - toolbox-streams-entity-preview
          - toolbox-streams-statement-enriched
          - toolbox-streams-rdf
      version:
        description: "Version"
        required: true
        type: string
      env:
        description: "To Environment"
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stag

jobs:
  inform-public-charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Echo env
        run: echo {{github.event.inputs.env}}

      - name: Invoke workflow in public-chart to make a release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-docker-image-tag
          repo: geovistory/public-chart
          ref: ${{github.event.inputs.env}}
          token: ${{ secrets.GEOVBOT_PAT_REPO }}
          inputs: |
            {
              "service": "${{github.event.inputs.app}}",
              "tag": "${{github.event.inputs.version}}",
              "environment": "${{github.event.inputs.env}}"
            }

