name: Test and Dockerize

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dockerize:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Extract number of pull request
        id: pull_request
        run: |
          echo ::set-output name=number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

      - name: Prints number of pull request
        run: echo Pull request branch is '${{ steps.pull_request.outputs.number }}'

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CHANNEL_WEBHOOK }}
          title: "Test and Dockerize"
          description: "PR: ${{ steps.pull_request.outputs.number }}"
          color: 0xffed2b
          username: GitHub Actions

      - name: Git Identity
        run: |
          git config --global user.name 'geovbot'
          git config --global user.email 'github.bot@geovistory.org'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # this will update metadata about PR for the docker tag in /build.gradle
      - name: Update pull request metadata in build.gradle
        id: version
        run: bash updatePRMetadata.bash ${{ steps.pull_request.outputs.number }}

      # This step will build a Java project with Gradle and cache/restore any dependencies  to improve
      # the workflow execution time. For more information see:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: app:build # "app:" points to /app

      # Create docker image
      - name: Create docker image
        run: ./gradlew app:jibDockerBuild

      # login to ghcr.io
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # push docker image
      - name: Push docker image
        run: docker push $(gradle -q app:printDockerImageTag)

      # commit the PR metadata updates
      - uses: EndBug/add-and-commit@v5
        with:
          message: 'chore(): update pr metadata'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CHANNEL_WEBHOOK }}
          title: "Dockerize > Done"
          description: "Image Tag: ${{steps.npm_version.outputs.tag}}"
          color: 0x0000ff
          username: GitHub Actions

